-- 旦Link 测试数据：与 001_initial_schema.sql + 前端 HomeScreen/LoginScreen/PublishTaskScreen 逻辑一致
-- profiles: 与 LoginScreen MOCK_USERS 对齐（学号、姓名、头像、院系、届、余额）；id 由表默认 gen_random_uuid()
-- tasks: category_tag 仅用 #外卖/#二手/#辅导/#跑腿（前端 filter 用 categoryTag.includes(selectedCategory)）
--        type: delivery(外卖/跑腿), study(二手), tutor(辅导)；price_label: 二手=售价，辅导=时薪，其余=酬劳

-- ========== 1. 插入 5 个虚拟复旦学生（与前端 LoginScreen MOCK_USERS 一致，便于联调）==========
INSERT INTO public.profiles (student_id, name, major, year, balance, avatar_url, rating)
VALUES
  ('21302010001', '张伟', '计算机科学技术学院', '21届', 1240, 'https://lh3.googleusercontent.com/aida-public/AB6AXuC_IEv6aRsK0zxLgHlRxhHnqWQ_kjVVQjNju4tgNbZkfeoHi-s-g9LJjaolyGA3gblPMF-yTA4osLYYzxXGOUjmggwmuOyM6Bik0dzOSDzzEJx9o-78MxlCnTfnh_itoChDZPo3ZmBMbziJ1Evy6k2ZNdSS67i8YzKro5wOx47qKxwKMiX2L5K_p4ZSvHl6dc_X-LicTZJDPNOWJBzLp3G_aCSIsYGcgWHzuw4tI_4tR4acmWcuSVggBB4r03IVYbELxHEO3z-AcxyF', 4.9),
  ('21302010002', '李华', '物理学系', '21届', 560, 'https://lh3.googleusercontent.com/aida-public/AB6AXuB5CRjpipLhLaAMQhev96yIXWSmU0spV4xuRMLxui2tQ6GV4wLrrf811_Wx8C2gfveNsksm3PDSzUiSeQ369Rq7UNEatsuNCqHsEPiO9SqIkiAL3CSl6U4O0SVQP8Zr4RygCO5V8XBWxdb9a4lsgUgr8VJdlpCqo_SAPkNsBA6jgxKDMp0P_60oixqBjYH7lvX7cfYo_dsXwtdLRe5E1Rc7j3dfoSjUZ9Amb56NWpLldNdZCkzQuUKzMa789RXFS4mycQyjEmv8GTQa', 4.8),
  ('22301010003', '林悦', '新闻学院', '22届', 880, 'https://lh3.googleusercontent.com/aida-public/AB6AXuAKWAmfDt9PS1X0KbAVTbZFTBLxirLSSnZ2lpQI2jGHF0F9o0_9OFxXBv3EjGj0vByBIrzWdlM968z2CSZwHo9kZ_A2lONczTgnaw7h2XptZ5DKL8In-6HEMw7HBIHXYGN-27ARuhqrQ7FfefGzv5KdlV1J6BgkZOP39displrArJZaiawyEi1at7dOF513bK0cPhRUNsxqlxPTdt2MNq_0pTLDL1pmIoBG7iTYVYXq8KsnajElS30chbtZomvC8cGr4uZd3lF-XXnJ', 5.0),
  ('22402010004', '王芳', '经济学院', '22届', 720, 'https://api.dicebear.com/7.x/avataaars/svg?seed=wangfang', 4.7),
  ('23102010005', '陈明', '数学科学学院', '23届', 100, 'https://api.dicebear.com/7.x/avataaars/svg?seed=chenming', 4.9)
ON CONFLICT (student_id) DO NOTHING;

-- ========== 2. 插入 20 条校园互助任务 ==========
-- category_tag 仅用 #外卖 | #二手 | #辅导 | #跑腿（与 HomeScreen categories 过滤一致）
-- type: delivery(外卖/跑腿), study(二手), tutor(辅导)；price_label: 二手=售价，辅导=时薪，其余=酬劳
-- status: 仅 active / completed（与 task_status 枚举一致），created_at 过去 24 小时内
INSERT INTO public.tasks (publisher_id, type, title, price_display, price_label, location_tag, category_tag, distance, description, start_label, end_label, quick_replies, status, created_at)
VALUES
  ((SELECT id FROM public.profiles ORDER BY random() LIMIT 1), 'delivery', '代取外卖', '¥8', '酬劳', '邯郸', '#外卖', '校内', '北区菜鸟驿站取一个包裹送到本部10号楼，小件，下午前。', '北区菜鸟驿站', '本部10号楼', '["📍 大概多大？","🕒 几点前要？"]'::jsonb, (array['active','active','completed'])[1 + floor(random() * 3)::int]::public.task_status, now() - random() * interval '24 hours'),
  ((SELECT id FROM public.profiles ORDER BY random() LIMIT 1), 'delivery', '代取外卖', '¥10', '酬劳', '邯郸', '#外卖', '校内', '东门快递点取两件快递送到江湾校区法学楼，明天上午。', '东门快递点', '江湾校区法学楼', '[]'::jsonb, (array['active','active','completed'])[1 + floor(random() * 3)::int]::public.task_status, now() - random() * interval '24 hours'),
  ((SELECT id FROM public.profiles ORDER BY random() LIMIT 1), 'delivery', '代取外卖', '¥6', '酬劳', '邯郸', '#外卖', '校内', '旦苑食堂带一份盖浇饭到光华楼西辅楼，12点前。', '旦苑食堂', '光华楼西辅楼', '["🕒 几点要？","🌶 要辣吗？"]'::jsonb, (array['active','active'])[1 + floor(random() * 2)::int]::public.task_status, now() - random() * interval '24 hours'),
  ((SELECT id FROM public.profiles ORDER BY random() LIMIT 1), 'delivery', '代取外卖', '¥5', '酬劳', '邯郸', '#外卖', '校内', '本部食堂带一份面到六教，下午一点前。', '本部食堂', '六教', '[]'::jsonb, (array['active','completed'])[1 + floor(random() * 2)::int]::public.task_status, now() - random() * interval '24 hours'),
  ((SELECT id FROM public.profiles ORDER BY random() LIMIT 1), 'delivery', '代取外卖', '¥12', '酬劳', '邯郸', '#外卖', '校内', '东门取外卖送到北苑4号楼，一份沙拉，不重。', '东门取货点', '北苑4号楼', '["🕒 多久能到？"]'::jsonb, (array['active','completed'])[1 + floor(random() * 2)::int]::public.task_status, now() - random() * interval '24 hours'),
  ((SELECT id FROM public.profiles ORDER BY random() LIMIT 1), 'delivery', '校内跑腿', '¥15', '酬劳', '邯郸', '#跑腿', '校内', '北区菜鸟驿站取一个中等纸箱送到相辉堂附近，今天傍晚。', '北区菜鸟驿站', '相辉堂', '["📦 大概多重？"]'::jsonb, (array['active','active'])[1 + floor(random() * 2)::int]::public.task_status, now() - random() * interval '24 hours'),
  ((SELECT id FROM public.profiles ORDER BY random() LIMIT 1), 'delivery', '校内跑腿', '¥3', '酬劳', '邯郸', '#跑腿', '校内', '文科图书馆借一本《传播学概论》送到光华楼，明天下午。', '文科图书馆', '光华楼', '[]'::jsonb, (array['active','active','completed'])[1 + floor(random() * 3)::int]::public.task_status, now() - random() * interval '24 hours'),
  ((SELECT id FROM public.profiles ORDER BY random() LIMIT 1), 'delivery', '校内跑腿', '¥2', '酬劳', '邯郸', '#跑腿', '校内', '帮我还一本高数教材到理科图书馆，今天闭馆前。', '本部10号楼', '理科图书馆', '[]'::jsonb, 'active', now() - random() * interval '24 hours'),
  ((SELECT id FROM public.profiles ORDER BY random() LIMIT 1), 'delivery', '校内跑腿', '¥5', '酬劳', '邯郸', '#跑腿', '校内', '文图帮我取桌上的一本《新闻学概论》送到相辉堂。', '文科图书馆', '相辉堂', '[]'::jsonb, (array['active','completed'])[1 + floor(random() * 2)::int]::public.task_status, now() - random() * interval '24 hours'),
  ((SELECT id FROM public.profiles ORDER BY random() LIMIT 1), 'delivery', '校内跑腿', '¥6', '酬劳', '邯郸', '#跑腿', '校内', '北区快递柜取一个小件送到东区18宿舍。', '北区快递柜', '东区18宿舍', '[]'::jsonb, (array['active','completed'])[1 + floor(random() * 2)::int]::public.task_status, now() - random() * interval '24 hours'),
  ((SELECT id FROM public.profiles ORDER BY random() LIMIT 1), 'delivery', '校内跑腿', '¥8', '酬劳', '邯郸', '#跑腿', '跨校区', '理图借一本《数学分析》送到江湾校区。', '理科图书馆', '江湾校区', '["🕒 明天可以吗？"]'::jsonb, (array['active','completed'])[1 + floor(random() * 2)::int]::public.task_status, now() - random() * interval '24 hours'),
  ((SELECT id FROM public.profiles ORDER BY random() LIMIT 1), 'study', '闲置交易', '¥25', '售价', '邯郸', '#二手', '校内', '出高数第七版教材，九成新，本部或北区面交。', '北区宿舍', '本部10号楼', '["📚 有笔记吗？","💰 能便宜吗？"]'::jsonb, (array['active','active','completed'])[1 + floor(random() * 3)::int]::public.task_status, now() - random() * interval '24 hours'),
  ((SELECT id FROM public.profiles ORDER BY random() LIMIT 1), 'study', '闲置交易', '¥180', '售价', '江湾', '#二手', '校内', '出二手自行车，江湾校区自提，代步用。', '江湾生活园区', '江湾生活园区', '[]'::jsonb, (array['active','completed'])[1 + floor(random() * 2)::int]::public.task_status, now() - random() * interval '24 hours'),
  ((SELECT id FROM public.profiles ORDER BY random() LIMIT 1), 'study', '闲置交易', '¥20', '售价', '邯郸', '#二手', '校内', '出《电磁学》课本，物理系用，光华楼或三教面交。', '光华楼', '三教', '["📍 哪里取？"]'::jsonb, 'active', now() - random() * interval '24 hours'),
  ((SELECT id FROM public.profiles ORDER BY random() LIMIT 1), 'study', '闲置交易', '¥30', '售价', '邯郸', '#二手', '校内', '出曼昆《经济学原理》第七版，经院用书，六教或旦苑面交。', '六教', '旦苑食堂', '[]'::jsonb, 'active', now() - random() * interval '24 hours'),
  ((SELECT id FROM public.profiles ORDER BY random() LIMIT 1), 'study', '闲置交易', '¥35', '售价', '江湾', '#二手', '校内', '出护眼台灯，江湾自提。', '江湾生活园区', '江湾生活园区', '[]'::jsonb, (array['active','active'])[1 + floor(random() * 2)::int]::public.task_status, now() - random() * interval '24 hours'),
  ((SELECT id FROM public.profiles ORDER BY random() LIMIT 1), 'study', '闲置交易', '¥28', '售价', '邯郸', '#二手', '校内', '出《数据结构》严蔚敏版，计院用，本部10号楼面交。', '本部10号楼', '本部10号楼', '["📚 有习题答案吗？"]'::jsonb, 'active', now() - random() * interval '24 hours'),
  ((SELECT id FROM public.profiles ORDER BY random() LIMIT 1), 'tutor', '课业辅导', '¥50', '时薪', '张江', '#辅导', '校内', '大一新生求助！数据结构的大作业卡住了，关于二叉树遍历的部分报错修不好。希望有学长学姐能当面指导一下，大概1小时。地点在食堂或咖啡厅都行。', '张江食堂', '咖啡厅', '["💻 线上还是线下？","🕒 今晚有空"]'::jsonb, (array['active','active'])[1 + floor(random() * 2)::int]::public.task_status, now() - random() * interval '24 hours'),
  ((SELECT id FROM public.profiles ORDER BY random() LIMIT 1), 'tutor', '课业辅导', '¥45', '时薪', '邯郸', '#辅导', '校内', '高数期中复习，希望有学长能帮忙串一下极限与导数，约1.5小时，光华楼或三教。', '光华楼', '三教', '["🕒 周末可以吗？"]'::jsonb, 'active', now() - random() * interval '24 hours'),
  ((SELECT id FROM public.profiles ORDER BY random() LIMIT 1), 'tutor', '课业辅导', '¥40', '时薪', '江湾', '#辅导', '校内', '法学专业课笔记整理求助，有偿请同学帮忙梳理重点，江湾法学楼。', '江湾法学楼', '江湾法学楼', '[]'::jsonb, (array['active','completed'])[1 + floor(random() * 2)::int]::public.task_status, now() - random() * interval '24 hours');
